database:
  host: localhost
  port: 5432
  user: postgres
  password: PostgresPassword
  db_name: easypeekdb
  ssl_mode: disable
  max_idle_conns: 10
  max_open_conns: 10

redis:
  address: localhost:6379
  password: ""
  database: 0

jwt:
  secret_key: "your-secret-key-here-change-in-production"
  expire_hours: 24

cors:
  allow_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
    - "*"

# 管理员初始化配置 (也可以通过环境变量设置)
admin:
  email: "admin@easypeek.com"
  username: "admin" 
  password: "admin123456" # 请在生产环境中更改默认密码

# AI服务配置
ai:
  provider: "openrouter"
  api_key: "YOUR_VALID_OPENROUTER_API_KEY_HERE" # 请替换为有效的OpenRouter API Key
  base_url: "https://openrouter.ai/api/v1"
  model: "google/gemini-2.0-flash-001" # 使用更稳定的thinking版本
  timeout: 30 
  max_tokens: 4000 # 增加token限制以获得更完整的响应
  temperature: 0.7
  # OpenRouter特有配置
  site_url: "http://localhost:5173/" # 你的网站URL（OpenRouter需要）
  site_name: "EasyPeek" # 你的应用名称（OpenRouter需要）
  # 自动分析配置
  auto_analysis:
    enabled: true # 是否启用自动AI分析
    analyze_on_fetch: true # 在RSS抓取时即时分析
    batch_process_interval: 15 # 批处理未分析新闻的间隔（分钟）- 增加间隔避免速率限制
    max_batch_size: 5 # 每次批处理的最大新闻数量 - 减少数量避免速率限制
    analysis_delay: 3 # 每个分析之间的延迟（秒）- 增加延迟避免速率限制

