database:
  host: localhost
  port: 5432
  user: postgres
  password: PostgresPassword
  db_name: easypeekdb
  ssl_mode: disable
  max_idle_conns: 10
  max_open_conns: 10

redis:
  address: localhost:6379
  password: ""
  database: 0

jwt:
  secret_key: "your-secret-key-here-change-in-production"
  expire_hours: 24

cors:
  allow_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
    - "*"

# 管理员初始化配置 (也可以通过环境变量设置)
admin:
  email: "admin@easypeek.com"
  username: "admin" 
  password: "admin123456" # 请在生产环境中更改默认密码

# AI 配置
ai:
  provider: "openrouter"
  api_key: ""  # 将从环境变量OPENAI_API_KEY读取
  base_url: "https://openrouter.ai/api/v1"
  model: "google/gemini-2.5-flash-preview"
  timeout: 30
  max_tokens: 4000
  temperature: 0.7
  site_url: "http://localhost:5173/"
  site_name: "EasyPeek"
  auto_analysis:
    enabled: true
    analyze_on_fetch: true
    batch_process_interval: 15  # 分钟
    max_batch_size: 50
    analysis_delay: 5  # 秒


