database:
  host: localhost
  port: 5432
  user: postgres
  password: PostgresPassword
  db_name: easypeekdb
  ssl_mode: disable
  max_idle_conns: 10
  max_open_conns: 10

redis:
  address: localhost:6379
  password: ""
  database: 0

jwt:
  secret_key: "your-secret-key-here-change-in-production"
  expire_hours: 24

cors:
  allow_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
    - "*"

open_router:
  api_key: "your-open-router-api-key-here"
  api_host: "https://openrouter.ai/api/v1"
  model: "openai/gpt-3.5-turbo" # You can choose any model supported by OpenRouter

